### Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.13.1'

In [6]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [10]:
print(result)

b'Hello World'


In [11]:
a = tf.constant(10)
b = tf.constant(20)

In [12]:
print(a+b)

Tensor("add_1:0", shape=(), dtype=int32)


In [13]:
type(a+b)

tensorflow.python.framework.ops.Tensor

In [14]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
print(result)

30


In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [19]:
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))

In [20]:
#Normal distribution
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [21]:
#Uniform distribution
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
#Run all these operation in the sessions

myops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [25]:
sess = tf.InteractiveSession()
for op in myops:
    print(sess.run(op)) #op.eval()
    print('\n')
tf.InteractiveSession().close()

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.32565948  0.2792701   1.2784711   2.307438  ]
 [ 0.528205   -0.6786119   0.15587185  0.2022807 ]
 [ 0.3209294   1.6624342  -0.9637534  -0.60288876]
 [ 0.29562098  1.2839406  -0.30809346  0.18194263]]


[[0.49491847 0.04683971 0.32782912 0.4792974 ]
 [0.12101638 0.5947342  0.07419336 0.09069097]
 [0.2520994  0.79031575 0.59836185 0.67170763]
 [0.03613496 0.65014386 0.34258306 0.25050378]]




C:\Users\lakshmsu\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [27]:
#Matrix multiplication
a = tf.constant([[1,2],
                [3,4]])

In [28]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([[10],[100]])

In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
result = tf.matmul(a,b)
sess.run(result)

array([[210],
       [430]])

In [34]:
result.eval()

array([[210],
       [430]])